name: Unwind Studios
favicon: null
layout_spectrum: 0.20780773391015828
typography_spectrum: 0.581704584416002
title: Unwind Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.02806088817305863
  lightness: 0.8231960267294198
  saturation: 0.9638859631959349
  rhythmicContrast: 0.026967059588059783
purpose: []
