name: Unwind Studios
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26743
title: Unwind Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#264673'
    - '#9ea1a3'
    - '#d1d3d4'
    - '#5684a9'
    - '#20a2dc'
  brandStrength: 0
  lightness: 1
  saturation: 0.9638859631959349
  rhythmicContrast: 0
purpose: []
